name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Android SDK
      run: |
        echo "sdk.dir=/usr/local/share/android-sdk" > local.properties
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        sudo apt-get install -y android-sdk
        sudo apt-get install -y gradle
        sdkmanager --update
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk
